# Generated by Django 3.1.6 on 2021-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_auto_20210212_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
